title: Necro
description: We're bringing AI-generated art to game development.
theme: just-the-docs

url: https://wkwan.github.io/necro

aux_links:
  Template Repository: https://github.com/wkwan/necro-doc
